// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample
{
    using Microsoft.Rest.Azure;
    using Models;

    /// <summary>
    /// Extension methods for ApiVersionDefaultOperations.
    /// </summary>
    public static partial class ApiVersionDefaultOperationsExtensions
    {
            /// <summary>
            /// GET method with api-version modeled in global settings.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static void GetMethodGlobalValid(this IApiVersionDefaultOperations operations)
            {
                ((IApiVersionDefaultOperations)operations).GetMethodGlobalValidAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// GET method with api-version modeled in global settings.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task GetMethodGlobalValidAsync(this IApiVersionDefaultOperations operations, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                (await operations.GetMethodGlobalValidWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// GET method with api-version modeled in global settings.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static void GetMethodGlobalNotProvidedValid(this IApiVersionDefaultOperations operations)
            {
                ((IApiVersionDefaultOperations)operations).GetMethodGlobalNotProvidedValidAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// GET method with api-version modeled in global settings.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task GetMethodGlobalNotProvidedValidAsync(this IApiVersionDefaultOperations operations, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                (await operations.GetMethodGlobalNotProvidedValidWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// GET method with api-version modeled in global settings.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static void GetPathGlobalValid(this IApiVersionDefaultOperations operations)
            {
                ((IApiVersionDefaultOperations)operations).GetPathGlobalValidAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// GET method with api-version modeled in global settings.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task GetPathGlobalValidAsync(this IApiVersionDefaultOperations operations, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                (await operations.GetPathGlobalValidWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// GET method with api-version modeled in global settings.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static void GetSwaggerGlobalValid(this IApiVersionDefaultOperations operations)
            {
                ((IApiVersionDefaultOperations)operations).GetSwaggerGlobalValidAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// GET method with api-version modeled in global settings.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task GetSwaggerGlobalValidAsync(this IApiVersionDefaultOperations operations, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                (await operations.GetSwaggerGlobalValidWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
