parameters:
  "service-dir":
    default: "sdk/hybridkubernetes"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/connectedClusters.json"
    examples-dir: "{project-root}/examples"
  "@azure-tools/typespec-csharp":
    flavor: azure
    package-dir: "Azure.ResourceManager.Kubernetes"
    clear-output-folder: true
    model-namespace: true
    namespace: "{package-dir}"
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-hybridkubernetes"
    namespace: "azure.mgmt.hybridkubernetes"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-hybridkubernetes"
    namespace: "com.azure.resourcemanager.hybridkubernetes"
    service-name: "Hybridkubernetes" # human-readable service name, whitespace allowed
    flavor: azure
  "@azure-tools/typespec-ts":
    package-dir: "arm-hybridkubernetes"
    is-modular-library: true
    flavor: "azure"
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-hybridkubernetes"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/hybridkubernetes"
    package-dir: "armhybridkubernetes"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-powershell":
    service-dir: "src"
    package-dir: "HybridKubernetes/HybridKubernetes.Autorest"
    clear-output-folder: true
    azure: true
    module-version: 0.1.0
    prefix: 'Az'
    subject-prefix: 'HybridKubernetes'
    service-name: HybridKubernetes
    module-name: "{prefix}.{service-name}"
    emit-modeler-output: true
    # output-folder: "{output-dir}"
    exclude-tableview-properties:
      - Id
      - Type
    directive:
      - where:
          subject: Operation
        hide: true
      - where:
          parameter-name: SubscriptionId
        set:
          default:
            script: '(Get-AzContext).Subscription.Id'
  # Following are common directives which are normally required in all the RPs
  # 1. Remove the unexpanded parameter set
  # 2. For New-* cmdlets, ViaIdentity is not required
      - where:
          variant: ^(Create|Update)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          variant: ^CreateViaIdentity.*$
        remove: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
