// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample
{
    using Microsoft.Rest.Azure;
    using Models;

    /// <summary>
    /// Extension methods for PetsOperations.
    /// </summary>
    public static partial class PetsOperationsExtensions
    {
            /// <summary>
            /// Create a Pet which contains more properties than what is defined.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='createParameters'>
            /// The ID of the target subscription.
            /// </param>
            public static PetAPTrue CreateAPTrue(this IPetsOperations operations, PetAPTrue createParameters)
            {
                return ((IPetsOperations)operations).CreateAPTrueAsync(createParameters).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create a Pet which contains more properties than what is defined.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='createParameters'>
            /// The ID of the target subscription.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<PetAPTrue> CreateAPTrueAsync(this IPetsOperations operations, PetAPTrue createParameters, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.CreateAPTrueWithHttpMessagesAsync(createParameters, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create a CatAPTrue which contains more properties than what is defined.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='createParameters'>
            /// </param>
            public static CatAPTrue CreateCatAPTrue(this IPetsOperations operations, CatAPTrue createParameters)
            {
                return ((IPetsOperations)operations).CreateCatAPTrueAsync(createParameters).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create a CatAPTrue which contains more properties than what is defined.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='createParameters'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<CatAPTrue> CreateCatAPTrueAsync(this IPetsOperations operations, CatAPTrue createParameters, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.CreateCatAPTrueWithHttpMessagesAsync(createParameters, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create a Pet which contains more properties than what is defined.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='createParameters'>
            /// </param>
            public static PetAPObject CreateAPObject(this IPetsOperations operations, PetAPObject createParameters)
            {
                return ((IPetsOperations)operations).CreateAPObjectAsync(createParameters).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create a Pet which contains more properties than what is defined.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='createParameters'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<PetAPObject> CreateAPObjectAsync(this IPetsOperations operations, PetAPObject createParameters, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.CreateAPObjectWithHttpMessagesAsync(createParameters, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create a Pet which contains more properties than what is defined.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='createParameters'>
            /// </param>
            public static PetAPString CreateAPString(this IPetsOperations operations, PetAPString createParameters)
            {
                return ((IPetsOperations)operations).CreateAPStringAsync(createParameters).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create a Pet which contains more properties than what is defined.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='createParameters'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<PetAPString> CreateAPStringAsync(this IPetsOperations operations, PetAPString createParameters, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.CreateAPStringWithHttpMessagesAsync(createParameters, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create a Pet which contains more properties than what is defined.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='createParameters'>
            /// </param>
            public static PetAPInProperties CreateAPInProperties(this IPetsOperations operations, PetAPInProperties createParameters)
            {
                return ((IPetsOperations)operations).CreateAPInPropertiesAsync(createParameters).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create a Pet which contains more properties than what is defined.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='createParameters'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<PetAPInProperties> CreateAPInPropertiesAsync(this IPetsOperations operations, PetAPInProperties createParameters, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.CreateAPInPropertiesWithHttpMessagesAsync(createParameters, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create a Pet which contains more properties than what is defined.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='createParameters'>
            /// </param>
            public static PetAPInPropertiesWithAPString CreateAPInPropertiesWithAPString(this IPetsOperations operations, PetAPInPropertiesWithAPString createParameters)
            {
                return ((IPetsOperations)operations).CreateAPInPropertiesWithAPStringAsync(createParameters).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create a Pet which contains more properties than what is defined.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='createParameters'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<PetAPInPropertiesWithAPString> CreateAPInPropertiesWithAPStringAsync(this IPetsOperations operations, PetAPInPropertiesWithAPString createParameters, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.CreateAPInPropertiesWithAPStringWithHttpMessagesAsync(createParameters, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
