// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample.Models
{
    using System.Linq;

    public partial class Dog
    {
        /// <summary>
        /// Initializes a new instance of the Dog class.
        /// </summary>
        public Dog()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Dog class.
        /// </summary>
        public Dog(bool? bark = default(bool?), string breed = default(string))
        {
            this.Bark = bark;
            this.Breed = breed;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "bark")]
        public bool? Bark { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "breed")]
        public string Breed { get; set; }

    }
}
