// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.ContainerRegistry.Models
{
    using System.Linq;

    /// <summary>
    /// The definition of a container registry operation.
    /// </summary>
    [Microsoft.Rest.Serialization.JsonTransformation]
    public partial class OperationDefinition
    {
        /// <summary>
        /// Initializes a new instance of the OperationDefinition class.
        /// </summary>
        public OperationDefinition()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OperationDefinition class.
        /// </summary>
        /// <param name="origin">The origin information of the container
        /// registry operation.</param>
        /// <param name="name">Operation name:
        /// {provider}/{resource}/{operation}.</param>
        /// <param name="display">The display information for the container
        /// registry operation.</param>
        /// <param name="serviceSpecification">The definition of Azure
        /// Monitoring service.</param>
        public OperationDefinition(string origin = default(string), string name = default(string), OperationDisplayDefinition display = default(OperationDisplayDefinition), OperationServiceSpecificationDefinition serviceSpecification = default(OperationServiceSpecificationDefinition))
        {
            this.Origin = origin;
            this.Name = name;
            this.Display = display;
            this.ServiceSpecification = serviceSpecification;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the origin information of the container registry
        /// operation.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "origin")]
        public string Origin { get; set; }

        /// <summary>
        /// Gets or sets operation name: {provider}/{resource}/{operation}.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the display information for the container registry
        /// operation.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "display")]
        public OperationDisplayDefinition Display { get; set; }

        /// <summary>
        /// Gets or sets the definition of Azure Monitoring service.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.serviceSpecification")]
        public OperationServiceSpecificationDefinition ServiceSpecification { get; set; }

    }
}
