// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.ContainerRegistry.Models
{
    using System.Linq;

    /// <summary>
    /// Run resource properties
    /// </summary>
    [Microsoft.Rest.Serialization.JsonTransformation]
    public partial class Run : ProxyResource
    {
        /// <summary>
        /// Initializes a new instance of the Run class.
        /// </summary>
        public Run()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Run class.
        /// </summary>
        /// <param name="id">The resource ID.</param>
        /// <param name="name">The name of the resource.</param>
        /// <param name="type">The type of the resource.</param>
        /// <param name="runId">The unique identifier for the run.</param>
        /// <param name="status">The current status of the run. Possible values
        /// include: 'Queued', 'Started', 'Running', 'Succeeded', 'Failed',
        /// 'Canceled', 'Error', 'Timeout'</param>
        /// <param name="lastUpdatedTime">The last updated time for the
        /// run.</param>
        /// <param name="runType">The type of run. Possible values include:
        /// 'QuickBuild', 'QuickRun', 'AutoBuild', 'AutoRun'</param>
        /// <param name="createTime">The time the run was scheduled.</param>
        /// <param name="startTime">The time the run started.</param>
        /// <param name="finishTime">The time the run finished.</param>
        /// <param name="outputImages">The list of all images that were
        /// generated from the run. This is applicable if the run generates
        /// base image dependencies.</param>
        /// <param name="task">The task against which run was
        /// scheduled.</param>
        /// <param name="imageUpdateTrigger">The image update trigger that
        /// caused the run. This is applicable if the task has base image
        /// trigger configured.</param>
        /// <param name="sourceTrigger">The source trigger that caused the
        /// run.</param>
        /// <param name="platform">The platform properties against which the
        /// run will happen.</param>
        /// <param name="agentConfiguration">The machine configuration of the
        /// run agent.</param>
        /// <param name="sourceRegistryAuth">The scope of the credentials that
        /// were used to login to the source registry during this run.</param>
        /// <param name="customRegistries">The list of custom registries that
        /// were logged in during this run.</param>
        /// <param name="runErrorMessage">The error message received from
        /// backend systems after the run is scheduled.</param>
        /// <param name="provisioningState">The provisioning state of a run.
        /// Possible values include: 'Creating', 'Updating', 'Deleting',
        /// 'Succeeded', 'Failed', 'Canceled'</param>
        /// <param name="isArchiveEnabled">The value that indicates whether
        /// archiving is enabled or not.</param>
        public Run(string id = default(string), string name = default(string), string type = default(string), string runType = default(string), string provisioningState = default(string), string runId = default(string), string status = default(string), System.DateTime? lastUpdatedTime = default(System.DateTime?), System.DateTime? createTime = default(System.DateTime?), System.DateTime? startTime = default(System.DateTime?), System.DateTime? finishTime = default(System.DateTime?), System.Collections.Generic.IList<ImageDescriptor> outputImages = default(System.Collections.Generic.IList<ImageDescriptor>), string task = default(string), ImageUpdateTrigger imageUpdateTrigger = default(ImageUpdateTrigger), SourceTriggerDescriptor sourceTrigger = default(SourceTriggerDescriptor), PlatformProperties platform = default(PlatformProperties), AgentProperties agentConfiguration = default(AgentProperties), string sourceRegistryAuth = default(string), System.Collections.Generic.IList<string> customRegistries = default(System.Collections.Generic.IList<string>), string runErrorMessage = default(string), bool? isArchiveEnabled = default(bool?))
            : base(id, name, type)
        {
            this.RunId = runId;
            this.Status = status;
            this.LastUpdatedTime = lastUpdatedTime;
            this.RunType = runType;
            this.CreateTime = createTime;
            this.StartTime = startTime;
            this.FinishTime = finishTime;
            this.OutputImages = outputImages;
            this.Task = task;
            this.ImageUpdateTrigger = imageUpdateTrigger;
            this.SourceTrigger = sourceTrigger;
            this.Platform = platform;
            this.AgentConfiguration = agentConfiguration;
            this.SourceRegistryAuth = sourceRegistryAuth;
            this.CustomRegistries = customRegistries;
            this.RunErrorMessage = runErrorMessage;
            this.ProvisioningState = provisioningState;
            this.IsArchiveEnabled = isArchiveEnabled;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the unique identifier for the run.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.runId")]
        public string RunId { get; set; }

        /// <summary>
        /// Gets or sets the current status of the run. Possible values
        /// include: 'Queued', 'Started', 'Running', 'Succeeded', 'Failed',
        /// 'Canceled', 'Error', 'Timeout'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets the last updated time for the run.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.lastUpdatedTime")]
        public System.DateTime? LastUpdatedTime { get; set; }

        /// <summary>
        /// Gets or sets the type of run. Possible values include:
        /// 'QuickBuild', 'QuickRun', 'AutoBuild', 'AutoRun'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.runType")]
        public string RunType { get; set; }

        /// <summary>
        /// Gets or sets the time the run was scheduled.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.createTime")]
        public System.DateTime? CreateTime { get; set; }

        /// <summary>
        /// Gets or sets the time the run started.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.startTime")]
        public System.DateTime? StartTime { get; set; }

        /// <summary>
        /// Gets or sets the time the run finished.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.finishTime")]
        public System.DateTime? FinishTime { get; set; }

        /// <summary>
        /// Gets or sets the list of all images that were generated from the
        /// run. This is applicable if the run generates base image
        /// dependencies.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.outputImages")]
        public System.Collections.Generic.IList<ImageDescriptor> OutputImages { get; set; }

        /// <summary>
        /// Gets or sets the task against which run was scheduled.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.task")]
        public string Task { get; set; }

        /// <summary>
        /// Gets or sets the image update trigger that caused the run. This is
        /// applicable if the task has base image trigger configured.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.imageUpdateTrigger")]
        public ImageUpdateTrigger ImageUpdateTrigger { get; set; }

        /// <summary>
        /// Gets or sets the source trigger that caused the run.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.sourceTrigger")]
        public SourceTriggerDescriptor SourceTrigger { get; set; }

        /// <summary>
        /// Gets or sets the platform properties against which the run will
        /// happen.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.platform")]
        public PlatformProperties Platform { get; set; }

        /// <summary>
        /// Gets or sets the machine configuration of the run agent.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.agentConfiguration")]
        public AgentProperties AgentConfiguration { get; set; }

        /// <summary>
        /// Gets or sets the scope of the credentials that were used to login
        /// to the source registry during this run.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.sourceRegistryAuth")]
        public string SourceRegistryAuth { get; set; }

        /// <summary>
        /// Gets or sets the list of custom registries that were logged in
        /// during this run.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.customRegistries")]
        public System.Collections.Generic.IList<string> CustomRegistries { get; set; }

        /// <summary>
        /// Gets the error message received from backend systems after the run
        /// is scheduled.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.runErrorMessage")]
        public string RunErrorMessage { get; private set; }

        /// <summary>
        /// Gets or sets the provisioning state of a run. Possible values
        /// include: 'Creating', 'Updating', 'Deleting', 'Succeeded', 'Failed',
        /// 'Canceled'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.provisioningState")]
        public string ProvisioningState { get; set; }

        /// <summary>
        /// Gets or sets the value that indicates whether archiving is enabled
        /// or not.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.isArchiveEnabled")]
        public bool? IsArchiveEnabled { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (this.Platform != null)
            {
                this.Platform.Validate();
            }
        }
    }
}
