// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.ContainerRegistry.Models
{
    using System.Linq;

    /// <summary>
    /// The properties for updating triggers.
    /// </summary>
    public partial class TriggerUpdateParameters
    {
        /// <summary>
        /// Initializes a new instance of the TriggerUpdateParameters class.
        /// </summary>
        public TriggerUpdateParameters()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TriggerUpdateParameters class.
        /// </summary>
        /// <param name="timerTriggers">The collection of timer
        /// triggers.</param>
        /// <param name="sourceTriggers">The collection of triggers based on
        /// source code repository.</param>
        /// <param name="baseImageTrigger">The trigger based on base image
        /// dependencies.</param>
        public TriggerUpdateParameters(System.Collections.Generic.IList<TimerTriggerUpdateParameters> timerTriggers = default(System.Collections.Generic.IList<TimerTriggerUpdateParameters>), System.Collections.Generic.IList<SourceTriggerUpdateParameters> sourceTriggers = default(System.Collections.Generic.IList<SourceTriggerUpdateParameters>), BaseImageTriggerUpdateParameters baseImageTrigger = default(BaseImageTriggerUpdateParameters))
        {
            this.TimerTriggers = timerTriggers;
            this.SourceTriggers = sourceTriggers;
            this.BaseImageTrigger = baseImageTrigger;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the collection of timer triggers.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "timerTriggers")]
        public System.Collections.Generic.IList<TimerTriggerUpdateParameters> TimerTriggers { get; set; }

        /// <summary>
        /// Gets or sets the collection of triggers based on source code
        /// repository.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "sourceTriggers")]
        public System.Collections.Generic.IList<SourceTriggerUpdateParameters> SourceTriggers { get; set; }

        /// <summary>
        /// Gets or sets the trigger based on base image dependencies.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "baseImageTrigger")]
        public BaseImageTriggerUpdateParameters BaseImageTrigger { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (this.TimerTriggers != null)
            {
                foreach (var element in this.TimerTriggers)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
            if (this.SourceTriggers != null)
            {
                foreach (var element1 in this.SourceTriggers)
                {
                    if (element1 != null)
                    {
                        element1.Validate();
                    }
                }
            }
            if (this.BaseImageTrigger != null)
            {
                this.BaseImageTrigger.Validate();
            }
        }
    }
}
