// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample
{
    using Microsoft.Rest.Azure;
    using Models;

    /// <summary>
    /// Extension methods for WorkspacesOperations.
    /// </summary>
    public static partial class WorkspacesOperationsExtensions
    {
            /// <summary>
            /// Creates a new workspace.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='workspace'>
            /// The workspace to create or update.
            /// </param>
            public static void CreateOrUpdate(this IWorkspacesOperations operations, Workspace workspace)
            {
                ((IWorkspacesOperations)operations).CreateOrUpdateAsync(workspace).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Creates a new workspace.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='workspace'>
            /// The workspace to create or update.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task CreateOrUpdateAsync(this IWorkspacesOperations operations, Workspace workspace, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                (await operations.CreateOrUpdateWithHttpMessagesAsync(workspace, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
