parameters:
  "service-dir":
    default: "sdk/chaos"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "resource-manager"
    emit-common-types-schema: "never"
    # `arm-resource-flattening` is only used for back-compat for specs existed on July 2024. All new service spec should NOT use this flag
    arm-resource-flattening: true
    emitter-output-dir: "{project-root}/.."
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
    omit-unreachable-types: true
    use-read-only-status-schema: true
  "@azure-tools/typespec-ts":
    experimental-extensible-enums: true
    package-dir: "arm-chaos"
    flavor: azure
    package-details:
      name: "@azure/arm-chaos"
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-chaos"
    namespace: "azure.mgmt.chaos"
    flavor: "azure"
    generate-test: true
    generate-sample: true
  "@azure-tools/typespec-csharp":
    flavor: azure
    package-dir: "Azure.ResourceManager.Chaos"
    clear-output-folder: true
    model-namespace: false
    namespace: "{package-dir}"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/chaos"
    package-dir: "armchaos"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-chaos"
    namespace: "com.azure.resourcemanager.chaos"
    service-name: "Chaos"
    flavor: "azure"
  "@azure-tools/typespec-powershell":
    service-dir: "src"
    package-dir: "Chaos/Chaos.Autorest"
    clear-output-folder: true
    debug: true
    azure: true
    module-version: 0.1.0
    prefix: "Az"
    subject-prefix: "Chaos"
    service-name: Chaos
    module-name: "{prefix}.{service-name}"
    # output-folder: "{output-dir}"
    emit-modeler-output: true
    exclude-tableview-properties:
      - Id
      - Type
    directive:
      - where:
          subject: Operation
        hide: true
      - where:
          parameter-name: SubscriptionId
        set:
          default:
            script: "(Get-AzContext).Subscription.Id"
      - where:
          variant: ^(Create|Update|Export)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          subject: MapConnection
          variant: ^(Get)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          variant: ^CreateViaIdentity$|^CreateViaIdentityExpanded$
        remove: true
      - where:
          verb: Set
        remove: true
      # Remove four post operations since there are issues in tsp and response schema are not defined.
      # - where:
      #     subject: MapConnection|MapDependencyView
      #     verb: Get
      #   remove: true
      # - where:
      #     verb: Export
      #   remove: true
      # - no-inline:
      #     - DiscoverySourceResourceProperties
      # - model-cmdlet:
      #     - model-name: OffAzureDiscoverySourceResourceProperties
      - where:
          subject: OperationStatuses
        remove: true

      - where:
          verb: Invoke
        set:
          verb: Get

      - model-cmdlet:
        - model-name: Selector
        - model-name: Step
        - model-name: Branch
        - model-name: Action
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
