// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample.Models
{
    using System.Linq;

    /// <summary>
    /// This is object
    /// </summary>
    public partial class OperationTypeObject
    {
        /// <summary>
        /// Initializes a new instance of the OperationTypeObject class.
        /// </summary>
        public OperationTypeObject()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OperationTypeObject class.
        /// </summary>
        public OperationTypeObject(string objectMember = default(string))
        {
            this.ObjectMember = objectMember;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "objectMember")]
        public string ObjectMember { get; set; }

    }
}
