parameters:
  "service-dir":
    default: "sdk/deviceprovisioningservices"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}"
    arm-types-dir: "{project-root}/../../../../common-types/resource-management"
    azure-resource-provider-folder: "resource-manager"
    output-file: "{version-status}/{version}/iotdps.json"
    examples-dir: "{project-root}/examples"
  "@azure-tools/typespec-csharp":
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
    flavor: azure
    clear-output-folder: true
    model-namespace: true
    namespace: "Azure.ResourceManager.DeviceProvisioningServices"
  "@azure-tools/typespec-python":
    service-dir: "sdk/iothub"
    package-dir: "azure-mgmt-iothubprovisioningservices"
    namespace: "azure.mgmt.iothubprovisioningservices"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-deviceprovisioningservices"
    namespace: "com.azure.resourcemanager.deviceprovisioningservices"
    service-name: "DeviceProvisioningServices" # human-readable service name, whitespace allowed
    flavor: azure
  "@azure-tools/typespec-ts":
    package-dir: "arm-deviceprovisioningservices"
    flavor: azure
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-deviceprovisioningservices"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/deviceprovisioningservices"
    package-dir: "armdeviceprovisioningservices"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-powershell":
    service-dir: "src"
    package-dir: "DeviceProvisioningServices/DeviceProvisioningServices.Autorest"
    clear-output-folder: true
    azure: true
    module-version: 0.1.0
    prefix: 'Az'
    subject-prefix: 'DeviceProvisioningServices'
    service-name: DeviceProvisioningServices
    module-name: "{prefix}.{service-name}"
    emit-modeler-output: true
    exclude-tableview-properties:
      - Id
      - Type
    directive:
      - where:
          subject: Operation
        hide: true
      - where:
          parameter-name: SubscriptionId
        set:
          default:
            script: '(Get-AzContext).Subscription.Id'
      - where:
          variant: ^(Create|Update)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          variant: ^CreateViaIdentity.*$
        remove: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
