// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample.Models
{
    using System.Linq;

    /// <summary>
    /// The object that contains details of encryption used on the workspace.
    /// </summary>
    public partial class Encryption
    {
        /// <summary>
        /// Initializes a new instance of the Encryption class.
        /// </summary>
        public Encryption()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Encryption class.
        /// </summary>
        /// <param name="keyName">The name of KeyVault key.</param>
        /// <param name="keyVersion">The version of KeyVault key.</param>
        /// <param name="keyVaultUri">The Uri of KeyVault.</param>
        public Encryption(string keyName = default(string), string keyVersion = default(string), string keyVaultUri = default(string))
        {
            this.KeyName = keyName;
            this.KeyVersion = keyVersion;
            this.KeyVaultUri = keyVaultUri;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the name of KeyVault key.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "KeyName")]
        public string KeyName { get; set; }

        /// <summary>
        /// Gets or sets the version of KeyVault key.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "keyversion")]
        public string KeyVersion { get; set; }

        /// <summary>
        /// Gets or sets the Uri of KeyVault.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "keyvaulturi")]
        public string KeyVaultUri { get; set; }

    }
}
