// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample.Models
{
    using System.Linq;

    public partial class ExtendedErrorModel : BasicErrorModel
    {
        /// <summary>
        /// Initializes a new instance of the ExtendedErrorModel class.
        /// </summary>
        public ExtendedErrorModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExtendedErrorModel class.
        /// </summary>
        public ExtendedErrorModel(string message, int code, string rootCause)
            : base(message, code)
        {
            this.RootCause = rootCause;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "rootCause")]
        public string RootCause { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public override void Validate()
        {
            base.Validate();
            if (this.RootCause == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "RootCause");
            }
        }
    }
}
