// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.ContainerService.Models
{

    /// <summary>
    /// Defines values for ResourceIdentityTypeForCommonTypes.
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum ResourceIdentityTypeForCommonTypes
    {
        [System.Runtime.Serialization.EnumMember(Value = "SystemAssigned")]
        SystemAssigned
    }
    internal static class ResourceIdentityTypeForCommonTypesEnumExtension
    {
        internal static string ToSerializedValue(this ResourceIdentityTypeForCommonTypes? value)
        {
            return value == null ? null : ((ResourceIdentityTypeForCommonTypes)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this ResourceIdentityTypeForCommonTypes value)
        {
            switch( value )
            {
                case ResourceIdentityTypeForCommonTypes.SystemAssigned:
                    return "SystemAssigned";
            }
            return null;
        }

        internal static ResourceIdentityTypeForCommonTypes? ParseResourceIdentityTypeForCommonTypes(this string value)
        {
            switch( value )
            {
                case "SystemAssigned":
                    return ResourceIdentityTypeForCommonTypes.SystemAssigned;
            }
            return null;
        }
    }
}
