parameters:
  "service-dir":
    default: "sdk/storageactions"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/storageactions.json"
    examples-dir: "{project-root}/examples"
  "@azure-tools/typespec-csharp":
    flavor: azure
    package-dir: "Azure.ResourceManager.StorageActions"
    clear-output-folder: true
    model-namespace: true
    namespace: "{package-dir}"
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-storageactions"
    namespace: "azure.mgmt.storageactions"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-storageactions"
    namespace: "com.azure.resourcemanager.storageactions"
    service-name: "StorageActions" # human-readable service name, whitespace allowed
    flavor: azure
  "@azure-tools/typespec-ts":
    package-dir: "arm-storageactions"
    is-modular-library: true
    flavor: "azure"
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-storageactions"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/storageactions"
    package-dir: "armstorageactions"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-powershell":
    service-dir: "src"
    package-dir: "StorageAction/StorageAction.Autorest"
    clear-output-folder: true
    azure: true
    module-version: 0.1.0
    prefix: 'Az'
    subject-prefix: 'StorageAction'
    service-name: StorageAction
    module-name: "{prefix}.{service-name}"
    # output-folder: "{output-dir}"
    emit-modeler-output: true
    exclude-tableview-properties:
      - Id
      - Type
    directive:
      - where:
          subject: Operation
        hide: true
      - where:
          parameter-name: SubscriptionId
        set:
          default:
            script: '(Get-AzContext).Subscription.Id'
      - where:
          variant: ^(Create|Update|Preview)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          variant: ^CreateViaIdentity$|^CreateViaIdentityExpanded$
        remove: true        
      - where:
          verb: Set
        remove: true  
      # Rename commands
      - where:
          subject: StorageTask
        set:
          subject: Task
      - where:
          verb: Invoke
          subject: PreviewStorageTaskAction
        set:
          subject: TaskPreviewAction
      - where:
          subject: StorageTaskAssignment
        set:
          subject: TaskAssignment
      - where:
          subject: StorageTasksReport
        set:
          subject: TasksReport
      # Add model
      - model-cmdlet:
        - model-name: StorageTaskOperation
          cmdlet-name: New-AzStorageActionTaskOperationObject
        - model-name: StorageTaskPreviewBlobProperties
          cmdlet-name: New-AzStorageActionTaskPreviewBlobPropertiesObject
        - model-name: StorageTaskPreviewKeyValueProperties
          cmdlet-name: New-AzStorageActionTaskPreviewKeyValuePropertiesObject
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"