parameters:
  "service-dir":
    default: "sdk/avs"
  "service-directory-name":
    default: "vmware"
emit: ["@azure-tools/typespec-autorest"]
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "resource-manager"
    emit-common-types-schema: "never"
    # `arm-resource-flattening` is only used for back-compat for specs existed on July 2024. All new service spec should NOT use this flag
    arm-resource-flattening: true
    emitter-output-dir: "{project-root}/.."
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/vmware.json"
    omit-unreachable-types: true
    use-read-only-status-schema: true

  "@azure-tools/typespec-csharp":
    flavor: azure
    package-dir: "Azure.ResourceManager.Avs"
    clear-output-folder: true
    model-namespace: true
    namespace: "{package-dir}"

  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/avs"
    package-dir: "armavs"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true

  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-avs"
    namespace: "com.azure.resourcemanager.avs"
    service-name: "Avs"
    flavor: azure
    use-object-for-unknown: true

  "@azure-tools/typespec-python":
    service-dir: "sdk/compute"
    package-dir: "azure-mgmt-avs"
    namespace: "azure.mgmt.avs"
    flavor: "azure"
    generate-test: true
    generate-sample: true

  "@azure-tools/typespec-ts":
    typespec-title-map:
      AzureVMwareSolutionAPIClient: AzureVMwareSolutionAPI
    experimental-extensible-enums: true
    package-dir: "arm-avs"
    flavor: "azure"
    package-details:
      name: "@azure/arm-avs"

  "@azure-tools/typespec-powershell":
    service-dir: "src"
    package-dir: "VMware/VMware.Autorest"
    clear-output-folder: true
    debug: true
    azure: true
    module-version: 0.1.0
    prefix: "Az"
    subject-prefix: "VMware"
    service-name: VMware
    module-name: "{prefix}.{service-name}"
    emit-modeler-output: true
    # output-folder: "{output-dir}"
    exclude-tableview-properties:
      - Id
      - Type
    directive:
      - where:
          subject: Operation
        hide: true
      - where:
          parameter-name: SubscriptionId
        set:
          default:
            script: "(Get-AzContext).Subscription.Id"
      - where:
          variant: ^(Create|Update|Export)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          subject: MapConnection
          variant: ^(Get)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          variant: ^CreateViaIdentity$|^CreateViaIdentityExpanded$
        remove: true
      - where:
          verb: Set
        remove: true
