emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    # `arm-resource-flattening` is only used for back-compat for specs existed on July 2024. All new service spec should NOT use this flag
    arm-resource-flattening: true
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/azurelargeinstance.json"
    use-read-only-status-schema: true
  "@azure-tools/typespec-powershell":
    service-dir: "src"
    package-dir: "AzureLargeInstance/AzureLargeInstance.Autorest"
    clear-output-folder: true
    azure: true
    module-version: 0.1.0
    skip-model-cmdlets: false
    help-link-prefix: https://learn.microsoft.com/powershell/module/
    metadata:
      authors: Microsoft Corporation
      owners: Microsoft Corporation
      description: 'Microsoft Azure PowerShell: AzureLargeInstance cmdlets'
      copyright: Microsoft Corporation. All rights reserved.
      tags: Azure ResourceManager ARM PSModule Sphere
      companyName: Microsoft Corporation
      requireLicenseAcceptance: true
      licenseUri: https://aka.ms/azps-license
      projectUri: https://github.com/Azure/azure-powershell
    prefix: 'Az'
    subject-prefix: 'AzureLargeInstance'
    service-name: AzureLargeInstance
    module-name: "{prefix}.{service-name}"
    namespace: "Microsoft.Azure.PowerShell.Cmdlets.{service-name}"
    use-namespace-folders: false
    # output-folder: "{output-dir}"
    exclude-tableview-properties:
      - Id
      - Type
    directive:
      - where:
          subject: Operation
        hide: true
      - where:
          parameter-name: SubscriptionId
        set:
          default:
            script: '(Get-AzContext).Subscription.Id'
      - where:
          variant: ^(Create|Update)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          verb: Set
        hide: true
