// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample.Models
{
    using System.Linq;

    /// <summary>
    /// Defines headers for customNamedRequestId operation.
    /// </summary>
    public partial class HeaderCustomNamedRequestIdHeaders
    {
        /// <summary>
        /// Initializes a new instance of the HeaderCustomNamedRequestIdHeaders
        /// class.
        /// </summary>
        public HeaderCustomNamedRequestIdHeaders()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HeaderCustomNamedRequestIdHeaders
        /// class.
        /// </summary>
        /// <param name="fooRequestId">Gets the foo-request-id.</param>
        /// <param name="ack">This is ack</param>
        public HeaderCustomNamedRequestIdHeaders(string fooRequestId = default(string), string ack = default(string))
        {
            this.FooRequestId = fooRequestId;
            this.Ack = ack;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the foo-request-id.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "foo-request-id")]
        public string FooRequestId { get; set; }

        /// <summary>
        /// Gets or sets this is ack
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ack")]
        public string Ack { get; set; }

    }
}
