// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample.Models
{
    using System.Linq;

    public partial class PetAPInPropertiesWithAPString
    {
        /// <summary>
        /// Initializes a new instance of the PetAPInPropertiesWithAPString
        /// class.
        /// </summary>
        public PetAPInPropertiesWithAPString()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PetAPInPropertiesWithAPString
        /// class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        public PetAPInPropertiesWithAPString(int id, string odatalocation, System.Collections.Generic.IDictionary<string, string> additionalProperties = default(System.Collections.Generic.IDictionary<string, string>), string name = default(string), bool? status = default(bool?), System.Collections.Generic.IDictionary<string, double?> additionalProperties1 = default(System.Collections.Generic.IDictionary<string, double?>))
        {
            this.AdditionalProperties = additionalProperties;
            this.Id = id;
            this.Name = name;
            this.Status = status;
            this.Odatalocation = odatalocation;
            this.AdditionalProperties1 = additionalProperties1;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, string> AdditionalProperties { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "status")]
        public bool? Status { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "@odata.location")]
        public string Odatalocation { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "additionalProperties")]
        public System.Collections.Generic.IDictionary<string, double?> AdditionalProperties1 { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (this.Odatalocation == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Odatalocation");
            }
        }
    }
}
