# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://learn.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master 

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    # ensure latest npm is installed
    npm install -g npm@9.8.1

    # make sure the versions are all synchronized and pull in dependencies
    npx @microsoft/rush sync-versions
    npx @microsoft/rush update 

    # set the actual package versions and update again
    if [ "$(skipSetVersion)" == "false" ]
    then
      npx @microsoft/rush set-versions
    else
      echo "Use the version set in package.json"
    fi
    npx @microsoft/rush sync-versions
    npx @microsoft/rush update 

    # compile the code
    npx @microsoft/rush rebuild 

    # build the packages
    npx @microsoft/rush publish --publish --pack --include-all --tag latest

    # publish the packages (tag as preview by default)
    echo "//registry.npmjs.org/:_authToken=$(azure-powershell-npm-token)" > ./.npmrc 
    for file in common/temp/artifacts/packages/*.tgz 
    do
     common/temp/pnpm-local/node_modules/.bin/pnpm publish $file --no-git-checks --tag latest --access public || echo no-worries 
    done

