// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample.Models
{

    /// <summary>
    /// Defines values for DataStringComparisonBehavior.
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum DataStringComparisonBehavior
    {
        [System.Runtime.Serialization.EnumMember(Value = "Ordinal")]
        Ordinal,
        [System.Runtime.Serialization.EnumMember(Value = "OrdinalIgnoreCase")]
        OrdinalIgnoreCase
    }
    internal static class DataStringComparisonBehaviorEnumExtension
    {
        internal static string ToSerializedValue(this DataStringComparisonBehavior? value)
        {
            return value == null ? null : ((DataStringComparisonBehavior)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this DataStringComparisonBehavior value)
        {
            switch( value )
            {
                case DataStringComparisonBehavior.Ordinal:
                    return "Ordinal";
                case DataStringComparisonBehavior.OrdinalIgnoreCase:
                    return "OrdinalIgnoreCase";
            }
            return null;
        }

        internal static DataStringComparisonBehavior? ParseDataStringComparisonBehavior(this string value)
        {
            switch( value )
            {
                case "Ordinal":
                    return DataStringComparisonBehavior.Ordinal;
                case "OrdinalIgnoreCase":
                    return DataStringComparisonBehavior.OrdinalIgnoreCase;
            }
            return null;
        }
    }
}
