// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample.Models
{
    using System.Linq;

    /// <summary>
    /// The response of the List Environments operation.
    /// </summary>
    public partial class EnvironmentListResponse
    {
        /// <summary>
        /// Initializes a new instance of the EnvironmentListResponse class.
        /// </summary>
        public EnvironmentListResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EnvironmentListResponse class.
        /// </summary>
        /// <param name="value">Result of the List Environments
        /// operation.</param>
        public EnvironmentListResponse(System.Collections.Generic.IList<EnvironmentResource> value = default(System.Collections.Generic.IList<EnvironmentResource>))
        {
            this.Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets result of the List Environments operation.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "value")]
        public System.Collections.Generic.IList<EnvironmentResource> Value { get; set; }

    }
}
