// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample.Models
{
    using System.Linq;

    /// <summary>
    /// An object that contains the details about an environment's state.
    /// </summary>
    public partial class EnvironmentStateDetails
    {
        /// <summary>
        /// Initializes a new instance of the EnvironmentStateDetails class.
        /// </summary>
        public EnvironmentStateDetails()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EnvironmentStateDetails class.
        /// </summary>
        /// <param name="code">Contains the code that represents the reason of
        /// an environment being in a particular state. Can be used to
        /// programmatically handle specific cases.</param>
        /// <param name="message">A message that describes the state in
        /// detail.</param>
        public EnvironmentStateDetails(string code = default(string), string message = default(string))
        {
            this.Code = code;
            this.Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets contains the code that represents the reason of an
        /// environment being in a particular state. Can be used to
        /// programmatically handle specific cases.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "code")]
        public string Code { get; set; }

        /// <summary>
        /// Gets or sets a message that describes the state in detail.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

    }
}
