// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample.Models
{
    using System.Linq;

    /// <summary>
    /// Parameters supplied to the Update Event Source operation to update an
    /// EventHub event source.
    /// </summary>
    [Microsoft.Rest.Serialization.JsonTransformation]
    public partial class EventHubEventSourceUpdateParameters : EventSourceUpdateParameters
    {
        /// <summary>
        /// Initializes a new instance of the
        /// EventHubEventSourceUpdateParameters class.
        /// </summary>
        public EventHubEventSourceUpdateParameters()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// EventHubEventSourceUpdateParameters class.
        /// </summary>
        /// <param name="tags">Key-value pairs of additional properties for the
        /// event source.</param>
        /// <param name="timestampPropertyName">The event property that will be
        /// used as the event source's timestamp. If a value isn't specified
        /// for timestampPropertyName, or if null or empty-string is specified,
        /// the event creation time will be used.</param>
        /// <param name="localTimestamp">An object that represents the local
        /// timestamp property. It contains the format of local timestamp that
        /// needs to be used and the corresponding timezone offset information.
        /// If a value isn't specified for localTimestamp, or if null, then the
        /// local timestamp will not be ingressed with the events.</param>
        /// <param name="sharedAccessKey">The value of the shared access key
        /// that grants the Time Series Insights service read access to the
        /// event hub. This property is not shown in event source
        /// responses.</param>
        public EventHubEventSourceUpdateParameters(string tags = default(string), LocalTimestamp localTimestamp = default(LocalTimestamp), string timestampPropertyName = default(string), string sharedAccessKey = default(string))
            : base(tags)
        {
            this.TimestampPropertyName = timestampPropertyName;
            this.LocalTimestamp = localTimestamp;
            this.SharedAccessKey = sharedAccessKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the event property that will be used as the event
        /// source's timestamp. If a value isn't specified for
        /// timestampPropertyName, or if null or empty-string is specified, the
        /// event creation time will be used.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.timestampPropertyName")]
        public string TimestampPropertyName { get; set; }

        /// <summary>
        /// Gets or sets an object that represents the local timestamp
        /// property. It contains the format of local timestamp that needs to
        /// be used and the corresponding timezone offset information. If a
        /// value isn't specified for localTimestamp, or if null, then the
        /// local timestamp will not be ingressed with the events.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.localTimestamp")]
        public LocalTimestamp LocalTimestamp { get; set; }

        /// <summary>
        /// Gets or sets the value of the shared access key that grants the
        /// Time Series Insights service read access to the event hub. This
        /// property is not shown in event source responses.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.sharedAccessKey")]
        public string SharedAccessKey { get; set; }

    }
}
