// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample.Models
{
    using System.Linq;

    /// <summary>
    /// An environment receives data from one or more event sources. Each event
    /// source has associated connection info that allows the Time Series
    /// Insights ingress pipeline to connect to and pull data from the event
    /// source
    /// </summary>
    [Newtonsoft.Json.JsonObject("EventSourceResource")]
    public partial class EventSourceResource : TrackedResource
    {
        /// <summary>
        /// Initializes a new instance of the EventSourceResource class.
        /// </summary>
        public EventSourceResource()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EventSourceResource class.
        /// </summary>
        /// <param name="location">Resource location</param>
        /// <param name="id">Resource Id</param>
        /// <param name="name">Resource name</param>
        /// <param name="type">Resource type</param>
        /// <param name="tags">Resource tags</param>
        public EventSourceResource(string location, string id = default(string), string name = default(string), string type = default(string), string tags = default(string))
            : base(location, id, name, type, tags)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
