// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample.Models
{

    /// <summary>
    /// Defines values for LocalTimestampFormat.
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum LocalTimestampFormat
    {
        [System.Runtime.Serialization.EnumMember(Value = "Embedded")]
        Embedded,
        [System.Runtime.Serialization.EnumMember(Value = "Iana")]
        Iana,
        [System.Runtime.Serialization.EnumMember(Value = "TimeSpan")]
        TimeSpan
    }
    internal static class LocalTimestampFormatEnumExtension
    {
        internal static string ToSerializedValue(this LocalTimestampFormat? value)
        {
            return value == null ? null : ((LocalTimestampFormat)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this LocalTimestampFormat value)
        {
            switch( value )
            {
                case LocalTimestampFormat.Embedded:
                    return "Embedded";
                case LocalTimestampFormat.Iana:
                    return "Iana";
                case LocalTimestampFormat.TimeSpan:
                    return "TimeSpan";
            }
            return null;
        }

        internal static LocalTimestampFormat? ParseLocalTimestampFormat(this string value)
        {
            switch( value )
            {
                case "Embedded":
                    return LocalTimestampFormat.Embedded;
                case "Iana":
                    return LocalTimestampFormat.Iana;
                case "TimeSpan":
                    return LocalTimestampFormat.TimeSpan;
            }
            return null;
        }
    }
}
