// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample.Models
{

    /// <summary>
    /// Defines values for PropertyType.
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum PropertyType
    {
        [System.Runtime.Serialization.EnumMember(Value = "String")]
        String,
        [System.Runtime.Serialization.EnumMember(Value = "123")]
        OneHundredTwentyThree
    }
    internal static class PropertyTypeEnumExtension
    {
        internal static string ToSerializedValue(this PropertyType? value)
        {
            return value == null ? null : ((PropertyType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this PropertyType value)
        {
            switch( value )
            {
                case PropertyType.String:
                    return "String";
                case PropertyType.OneHundredTwentyThree:
                    return "123";
            }
            return null;
        }

        internal static PropertyType? ParsePropertyType(this string value)
        {
            switch( value )
            {
                case "String":
                    return PropertyType.String;
                case "123":
                    return PropertyType.OneHundredTwentyThree;
            }
            return null;
        }
    }
}
