// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Sample.Models
{

    /// <summary>
    /// Defines values for StorageLimitExceededBehavior.
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum StorageLimitExceededBehavior
    {
        [System.Runtime.Serialization.EnumMember(Value = "PurgeOldData")]
        PurgeOldData,
        [System.Runtime.Serialization.EnumMember(Value = "PauseIngress")]
        PauseIngress
    }
    internal static class StorageLimitExceededBehaviorEnumExtension
    {
        internal static string ToSerializedValue(this StorageLimitExceededBehavior? value)
        {
            return value == null ? null : ((StorageLimitExceededBehavior)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this StorageLimitExceededBehavior value)
        {
            switch( value )
            {
                case StorageLimitExceededBehavior.PurgeOldData:
                    return "PurgeOldData";
                case StorageLimitExceededBehavior.PauseIngress:
                    return "PauseIngress";
            }
            return null;
        }

        internal static StorageLimitExceededBehavior? ParseStorageLimitExceededBehavior(this string value)
        {
            switch( value )
            {
                case "PurgeOldData":
                    return StorageLimitExceededBehavior.PurgeOldData;
                case "PauseIngress":
                    return StorageLimitExceededBehavior.PauseIngress;
            }
            return null;
        }
    }
}
