parameters:
  "service-dir":
    default: "sdk/devopsinfrastructure"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
  disable:
    "@azure-tools/typespec-azure-resource-manager/arm-common-types-version": "New rule"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    emit-common-types-schema: "never"
    # `arm-resource-flattening` is only used for back-compat for specs existed on July 2024. All new service spec should NOT use this flag
    arm-resource-flattening: true
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/devopsinfrastructure.json"
    omit-unreachable-types: true
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-devopsinfrastructure"
    package-name: "{package-dir}"
    flavor: "azure"
    generate-test: true
    generate-sample: true
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-devopsinfrastructure"
    flavor: "azure"
    namespace: "com.azure.resourcemanager.devopsinfrastructure"
    service-name: "DevOps Infrastructure"
  "@azure-tools/cadl-csharp":
    save-inputs: false
    clear-output-folder: true
    namespace: Microsoft.DevOpsInfrastructure
    model-namespace: false
  "@azure-tools/typespec-csharp":
    flavor: azure
    clear-output-folder: true
    package-dir: "Azure.ResourceManager.DevOpsInfrastructure"
    namespace: "{package-dir}"
  "@azure-tools/typespec-ts":
    azureSdkForJs: true
    isModularLibrary: true
    generateMetadata: true
    hierarchyClient: false
    experimentalExtensibleEnums: true
    enableOperationGroup: true
    package-dir: "arm-devopsinfrastructure"
    flavor: "azure"
    packageDetails:
      name: "@azure/arm-devopsinfrastructure"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/devopsinfrastructure"
    package-dir: "armdevopsinfrastructure"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    flavor: "azure"
    generate-examples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
    remove-unreferenced-types: true
  "@azure-tools/typespec-powershell":
    service-dir: "src"
    package-dir: "DevOpsInfrastructure/DevOpsInfrastructure.Autorest"
    clear-output-folder: true
    azure: true
    module-version: 0.1.0
    skip-model-cmdlets: false
    help-link-prefix: https://learn.microsoft.com/powershell/module/
    metadata:
      authors: Microsoft Corporation
      owners: Microsoft Corporation
      description: 'Microsoft Azure PowerShell: DevOpsInfrastructure cmdlets'
      copyright: Microsoft Corporation. All rights reserved.
      tags: Azure ResourceManager ARM PSModule Sphere
      companyName: Microsoft Corporation
      requireLicenseAcceptance: true
      licenseUri: https://aka.ms/azps-license
      projectUri: https://github.com/Azure/azure-powershell
    prefix: 'Az'
    subject-prefix: 'DevOpsInfrastructure'
    service-name: DevOpsInfrastructure
    module-name: "{prefix}.{service-name}"
    namespace: "Microsoft.Azure.PowerShell.Cmdlets.{service-name}"
    use-namespace-folders: false
    # output-folder: "{output-dir}"
    exclude-tableview-properties:
      - Id
      - Type
    directive:
      - where:
          subject: Operation
        hide: true
      - where:
          parameter-name: SubscriptionId
        set:
          default:
            script: '(Get-AzContext).Subscription.Id'
      - where:
          variant: ^(Create|Update)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          verb: Set
        hide: true